BEGIN;

-- Enable pgvector extension for vector similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding columns to insights table
-- Using vector(1024) for Voyage AI voyage-large-2 embeddings
ALTER TABLE public.insights
  ADD COLUMN IF NOT EXISTS content_embedding vector(1024),
  ADD COLUMN IF NOT EXISTS summary_embedding vector(1024),
  ADD COLUMN IF NOT EXISTS embedding_updated_at TIMESTAMPTZ;

-- Add embedding column to messages table (optional, for context)
ALTER TABLE public.messages
  ADD COLUMN IF NOT EXISTS content_embedding vector(1024);

-- Create HNSW index for fast similarity search on insights content
CREATE INDEX IF NOT EXISTS idx_insights_content_embedding_hnsw 
  ON public.insights 
  USING hnsw (content_embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- Create HNSW index for summary embeddings
CREATE INDEX IF NOT EXISTS idx_insights_summary_embedding_hnsw 
  ON public.insights 
  USING hnsw (summary_embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- Create index for messages embeddings (if needed)
CREATE INDEX IF NOT EXISTS idx_messages_content_embedding_hnsw 
  ON public.messages 
  USING hnsw (content_embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- Add comment for documentation
COMMENT ON COLUMN public.insights.content_embedding IS 'Vector embedding of insight content generated by Voyage AI (1024 dimensions)';
COMMENT ON COLUMN public.insights.summary_embedding IS 'Vector embedding of insight summary generated by Voyage AI (1024 dimensions)';
COMMENT ON COLUMN public.insights.embedding_updated_at IS 'Timestamp when embeddings were last generated or updated';

COMMIT;

-- //@UNDO
BEGIN;

-- Drop indexes
DROP INDEX IF EXISTS public.idx_messages_content_embedding_hnsw;
DROP INDEX IF EXISTS public.idx_insights_summary_embedding_hnsw;
DROP INDEX IF EXISTS public.idx_insights_content_embedding_hnsw;

-- Drop columns
ALTER TABLE public.messages
  DROP COLUMN IF EXISTS content_embedding;

ALTER TABLE public.insights
  DROP COLUMN IF EXISTS embedding_updated_at,
  DROP COLUMN IF EXISTS summary_embedding,
  DROP COLUMN IF EXISTS content_embedding;

-- Note: We don't drop the vector extension as it might be used by other tables
-- DROP EXTENSION IF EXISTS vector;

COMMIT;

