name: Database migrations

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
      - 'scripts/migrate.js'
      - '.github/workflows/database-migrations.yml'

concurrency:
  group: database-migrations
  cancel-in-progress: false

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
      PGSSLMODE: require
      PGSSLREJECTUNAUTHORIZED: 'false'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Apply database migrations
        run: npm run migrate

      - name: Show migration status
        run: npm run migrate:status
